### PR TITLE
Create hu.json

### PR DESCRIPTION
**Pull request by ovari**

### CODE REVIEW

**Comment by ovari** [comment]
@ilmartyrk will ep_image_upload be part of the Centralized translation repo for plugins?
https://github.com/ether/etherpad-lite/issues/4317

Thank you

**Comment by ilmartyrk** [comment]
@ovari I'll need to take a deeper look at it before I can confirm.  For our project we have developed a solution based on crowdin. I created a plugin https://github.com/citizenos/ep_translations that enables to sync translations from git repo. All translations are in https://github.com/citizenos/etherpad_translations. All translation keys for our plugins and etherpad are added to source.json. This is synced with crowdin as crowdin supports github integrations. Now all strings can be translated and reviewed and after they are confirmed crowdin creates a pull request into github reposistory. If pull is merged into master it is pulled into etherpad instance by ep_translations plugin. IF this Centralized repo is a better alternative for our case we will for sure use it, but we'll have to take a deeper look for how it influences our current work flow etc.

**Comment by ovari** [comment]
> For our project we have developed a solution based on crowdin

In the `README.md` file at https://github.com/citizenos/ep_image_upload/, can you please add a link to your [Crowdin](https://crowdin.com) page for this plugin?

Thank you

**Comment by ovari** [comment]
> IF this Centralized repo is a better alternative for our case we will for sure use it, but we'll have to take a deeper look for how it influences our current work flow etc.

Can you comment at https://github.com/ether/etherpad-lite/issues/4317 as this can help with the development?

**Comment by ilmartyrk** [comment]
@ovari there is no separate project in Crowdin for this plugin, but we have a project that includes all translation keys from our etherpad instane, project sits here https://crowdin.com/project/citizen-os-etherpad

**Comment by ovari** [comment]
Can https://crowdin.com/project/citizen-os-etherpad please be added to the `README.md`?

**Comment by ovari** [comment]
Can you please add `hu (Hungarian - magyar)` to https://crowdin.com/project/citizen-os-etherpad?

**Comment by ilmartyrk** [comment]
I will not add this Crowdin project link to README.md at least for now, but I've added Hungarian to Crowdin project

**Comment by ovari** [comment]
> I've added Hungarian to Crowdin project

Thanks. The strings are at 0%. Can you please upload the strings in this GitHub repository to Crowdin please?

**Pull request merged**
